### ISSUE TITLE
MUSCLE 多序列对比中... MUSCLE 多序列比对异常

### ISSUE THREAD

**Issue by Kishlaykumr** [AGIScuipeng/PMPrimer#9]
i m trying to align the file using the below code, however, I keep getting the error as mentioned below and no alignment sequences is saved as *.mc.fasta .  Could you please provide the solution to this? Many thanks. (FYI, i was able to run successfully the 16s data set file that you have described in the paper and wanted to try on different sequences!)

(base) kishay@ubuntu:~$ pmprimer -f Neisseria_G_M.fasta -a muscle
MUSCLE 多序列对比中...
MUSCLE 多序列比对异常
(base) kishay@ubuntu:~$

**Comment by Kishlaykumr** [comment]
![image](https://github.com/AGIScuipeng/PMPrimer/assets/160045219/33be13ae-e123-4e19-89bf-98a2db74aa0a)

![Pmprimer_run_cmd_results](https://github.com/AGIScuipeng/PMPrimer/assets/160045219/45102613-29e3-4827-9f31-3727ec17026b)
[Neisseria_G_M.txt](https://github.com/AGIScuipeng/PMPrimer/files/14283455/Neisseria_G_M.txt)

**Comment by N3R1UM** [comment]
The 1.0.5 version of the software does not include the muscle executable file when it is packaged. The 1.0.6 version has included the muscle executable file into the software package.
